# Render Blueprint for ISRO AQI Backend
# This file configures automatic deployment to Render

services:
  # PostgreSQL Database
  - type: pserv
    name: aqi-database
    plan: free
    databaseName: aqi_database
    user: aqi_user
    region: oregon

  # Backend Web Service  
  - type: web
    name: aqi-backend
    runtime: docker
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        fromDatabase:
          name: aqi-database
          property: connectionString
      - key: OPENWEATHER_API_KEY
        value: 54e72fa67053fd111f04bb90d633cca6
      - key: IQAIR_API_KEY  
        value: 7983aa7d-e986-481a-ac20-790546737b75
      - key: USE_REAL_DATA
        value: true
      - key: ENABLE_CRON_JOBS
        value: false
      - key: LOG_LEVEL
        value: info
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100

# Build configuration
buildCommand: npx prisma generate
startCommand: npx prisma migrate deploy && node server.js
